/* Header file for Lattice Class & LatticeObject functions, structs & enums
*  By Alex Allen & Daniel Liew (2010)
*/

#ifndef TWO_D_LATTICE
	
	#include "common.h"
	#include "directorelement.h"
	#include "nanoparticle.h"
	


	/* LatticeConfig is used to hold initial configuration parameters
	* for a lattice and should be passed to Lattice::Lattice();
	*
	*/
	typedef struct
	{
		/*
		* Although width & height should not be < 0
		* using unsigned int causes problems when comparing to signed ints
		* e.g. 
		* signed int x=5;
		* if(-4 < x) this is false if x is unsigned
		* need to do if( -4 < (signed int) x) to get true
		* 
		* We do not want to be doing typecasts everytime we do a comparision so just use
		* signed ints instead!
		*/
		signed int width;
		signed int height;

		/*
		* assume k_1 = 1
		* k_3 = beta* k_1
		*/
		double beta;


		/* These define the different type of boundary conditions on the edges of the lattice
		 * The BOUNDARY_PARALLEL & BOUNDARY_PERPENDICULAR conditions are relative to the x-axis
		 * and not the edge itself.
		 *
		 * For example if leftBoundary = BOUNDARY_PERPENDICULAR
		 * The left boundary will be perpendilcar to the x-axis and not to the left boundary edge
		*/
		enum latticeBoundary
		{
			BOUNDARY_PARALLEL,
			BOUNDARY_PERPENDICULAR,
			BOUNDARY_PERIODIC
		} topBoundary, bottomBoundary, leftBoundary, rightBoundary;


		enum latticeState
		{
			RANDOM,
			PARALLEL_X,
			PARALLEL_Y,

			/* K1_EQUAL_K3, K1_DOMINANT & K3_DOMINANT should be used in conjunction with
			*  param.bottomBoundary = LatticeConfig::BOUNDARY_PARALLEL
			*  param.topBoundary = LatticeConfig::BOUNDARY_PERPENDICULAR
			*
			*  These are the minimum free energy configurations for the analytical
			*  solutions using the above boundary conditions and assuming the behaviour of K_1 and K_3.
			*/
			K1_EQUAL_K3,
			K1_DOMINANT,
			K3_DOMINANT
		} initialState;

		/* Monte Carlo and coning algorithm parameters */

		double iTk;//Inverse "Temperature" of lattice for Monte Carlo algorithm
		unsigned long mStep; //The current Monte Carlo step number
		int acceptCounter, rejectCounter; //Counters used for coning algorithm
		double aAngle; //The current acceptance angle
		double desAcceptRatio; //The Desired acceptance ratio
 

	} LatticeConfig;


	class Lattice
	{
		private:
			int mNumNano; //The number of nanoparticles associated with this lattice
			Nanoparticle** mNanoparticles; //An array of pointers to the nanoparticles associated with this lattice
			bool badState;

			//Define the 2D lattice array (we use a linear memory block however)
			DirectorElement* lattice;
			
			const bool constructedFromFile;// Used to indicate which constructor was called
			const DirectorElement PARALLEL_DIRECTOR;
			const DirectorElement PERPENDICULAR_DIRECTOR;
			
			/* This DUMMY_DIRECTOR exists so that a pointer to something that isn't
			*  NULL is returned by getN() and setN() if an invalid point in the lattice
			*  is requested. It should be initialised to {0,0,0} but access via setN()
			*  can allow its value to be changed which the user "should" be warned about.
			*/
			const DirectorElement DUMMY_DIRECTOR; 

			//Helper function of calculateEnergyOfCell()
			double calculateCosineBetween(const DirectorElement* C, const DirectorElement* O, const double& flipSign);

		public:
			//Lattice Parameters
			LatticeConfig param;

			/* This initialises the lattice from a LatticeConfig struct
			* 
			*/
			Lattice(LatticeConfig configuration);
		
			/* Initialise lattice from a saved state file generated by
			*  the saveState() method.
			*/
			Lattice(const char* filename);

			~Lattice(); //destructor


			/* Adds a nanoparticle (np) (of type that should be derived from class Nanoparticle) to the lattice.
			*  The method will return true if successful or false if something goes wrong!
			*/
			bool add(Nanoparticle& np);

			/* This method returns a pointer to the "element" of the director field at (xPos, yPos) with the constraints of the 
			 * boundary conditions of a LatticeObject (theLattice). Note that if you wish to change the director value at point (x,y)
			 * you should use getN().
			*/
			const DirectorElement* getN(int xPos, int yPos) const;
		
			/* This is like getN() accept it allows you to change the director value at point (x,y).
			*  Use with CAUTION!
			*/
			DirectorElement * setN(int xPos, int yPos);

			/* This sets the state of the lattice to one of the initialState presets.
			*  Note: This only affects lattice cells that aren't marked as Nanoparticles.
			*/
			void reInitialise(enum LatticeConfig::latticeState initialState);

			/* These are the different dumping modes used by translatedUnitVectorDump()
			*  EVERYTHING - NANOPARTICLES AND NORMAL LATTICE POINTS
			*  PARTICLES - NANOPARTICLES ONLY
			*  NOT_PARTICLES - NORMAL LATTICE POINTS ONLY
			*/
			enum dumpMode
			{
				EVERYTHING, //prints entire lattice but not the boundary
				PARTICLES, //prints just the particles
				NOT_PARTICLES, //prints everything but the particles and boundary
				BOUNDARY //prints the boundary	
			};

			/*
			* This method outputs the current state of the lattice to filestream stream (e.g. stdout) in a format
			* compatible with the GNUplot script "ldump.gnu". The director field is plotted as
			* unit vectors that are translated so that the centre of the vector rather than the end of the vector
			* is plotted at point (xPos,yPos).
			*/
			void nDump(enum Lattice::dumpMode mode, std::ostream& stream) const;
			
			/* This method outputs the current state of the lattice to a filestream stream in a format compatible
			*  with the GNUplot script "ildump.gnu". It outputs three indexes.
			*  index 0 - BOUNDARY
			*  index 1 - NOT_PARTICLES 
			*  index 1 - PARTICLES
			*/
			void indexedNDump(std::ostream& stream) const;
			
			/* Dump a description of lattice parameters to out Output stream. E.g. std::cout
			*
			*/
			void dumpDescription(std::ostream& stream) const;

			/* Calculate the Free energy per unit area in the cell located at (xPos,yPos) in the lattice on the HOST!
			*/
			double calculateEnergyOfCell(int xPos, int yPos);
			
			/* Calculate the Free energy of the lattice on the HOST!
			*/
			double calculateTotalEnergy();

			//returns true if Lattice is in a bad state (usually from initialisation or add() )
			bool inBadState() const { return badState;}

			/* Saves binary state file to filename
			*/
			bool saveState(const char* filename);

			//overloaded comparison operator
			bool operator==(const Lattice & rhs) const;
			
			//overloaded != operator
			bool operator!=(const Lattice & rhs) const;
			

	};

	#define TWO_D_LATTICE 1	
#endif
